from app.core.module_types import (
    IntegrationEffect,
    IntegrationEffects,
    IntegrationSpec,
    MigrationSpec,
    ModuleSpec,
    ShareAsset,
    ShareRoute,
    ShareSpec,
)

MODULE = ModuleSpec(
    id="vault",
    version="0.1.0",
    title_en="Vault",
    title_ru="Хранилище / Заметки",
    dashboard_url="/vault/dashboard",
    order=30,
    router="app.modules.vault.router:router",
    models="app.modules.vault.models",
    migrations=MigrationSpec(
        path="migrations",
        baseline_revision="vault_0001",
        tables=("vault_collections", "vault_items"),
        legacy_tables=("vault_collections", "vault_items"),
    ),
    templates="templates",
    share=ShareSpec(
        provider="app.modules.vault.share:PROVIDER",
        selector_key="item_ids",
        dashboard_template="vault_dashboard.html",
        api_prefix="/api/vault",
        routes=(
            ShareRoute(name="items", path="items"),
            ShareRoute(name="item_detail", path="items/{item_id}"),
            ShareRoute(name="stats", path="stats"),
            ShareRoute(name="collections", path="collections", source="relations"),
        ),
        assets=(ShareAsset(name="item_image", path="items/{item_id}/image"),),
    ),
    module_cleanup="app.modules.vault.cleanup:cleanup_module",
    storage_namespaces=("vault",),
    package_prefixes=("vault_all",),
    package_resolver="app.modules.vault.capabilities:resolve_package_resources",
    integrations=(
        IntegrationSpec(
            id="vault.capture.v1",
            handler="app.modules.vault.integrations:capture_item",
            request_model="app.contracts.vault_capture_v1:VaultCaptureRequest",
            result_model="app.contracts.vault_capture_v1:VaultCaptureResult",
            description="Create a note or bookmark in Vault.",
            effects=IntegrationEffects(
                effect=IntegrationEffect.CREATE,
                reversible=True,
                undo_integration="vault.undo.v1",
            ),
        ),
        IntegrationSpec(
            id="vault.undo.v1",
            handler="app.modules.vault.integrations:undo_capture",
            request_model="app.contracts.undo_v1:UndoRequest",
            result_model="app.contracts.undo_v1:UndoResult",
            description="Remove a Vault entry that a previous capture created.",
            contract="undo.v1",
            effects=IntegrationEffects(
                effect=IntegrationEffect.DELETE,
                idempotent=True,
            ),
        ),
        IntegrationSpec(
            id="vault.search.documents.v1",
            contract="search.documents.v1",
            handler="app.modules.vault.search:search_documents",
            request_model="app.contracts.search_documents_v1:SearchDocumentsRequest",
            result_model="app.contracts.search_documents_v1:SearchDocumentsResult",
            description="Publish non-archived Vault items to the private search index.",
            effects=IntegrationEffects(effect=IntegrationEffect.READ, idempotent=True),
        ),
    ),
)
