import datetime
import json
import logging
import os
import random
import tempfile
import time

import redis
import yt_dlp
from sqlalchemy import select

from app.core.config import get_settings
from app.core.database import SyncSessionLocal
from app.core.remote_fetch import RemoteFetchError, fetch_bytes_checked
from app.core.scheduler import celery_app
from app.core.secret_values import decrypt_secret_value
from app.core.storage import get_storage
from app.core.task_dispatch import dispatch_tracked_sync
from app.modules.settings.models import Setting
from app.modules.video_archiver.models import ArchivedVideo, VideoChannel, VideoPlaylist
from app.modules.video_archiver.providers import PlatformRegistry

logger = logging.getLogger(__name__)
settings = get_settings()
VIDEO_IMAGE_HOSTS = frozenset(
    {
        "youtube.com",
        "ytimg.com",
        "googleusercontent.com",
        "ggpht.com",
        "userapi.com",
        "vkuser.net",
        "telegram-cdn.org",
        "boosty.to",
        "rutubelist.ru",
    }
)

# Initialize Redis client using dynamic REDIS_URL
redis_client = redis.Redis.from_url(settings.REDIS_URL, decode_responses=True)


def _get_platform_cookies(platform_id: str) -> str | None:
    """Fetch module cookies for a specific platform from settings DB."""
    with SyncSessionLocal() as session:
        setting = (
            session.query(Setting)
            .filter_by(
                key=f"{platform_id}_cookies",
                scope="module",
                module_name="video_archiver",
            )
            .first()
        )
        if setting and setting.value and setting.value.strip():
            return decrypt_secret_value(setting.value)
    return None


def _create_temp_cookies_file(cookies_text: str | None) -> str | None:
    """Write cookies to a temporary file if provided, ensuring Netscape header and unix line endings."""
    if cookies_text and cookies_text.strip():
        text = cookies_text.strip()
        if not text.startswith("# Netscape"):
            text = "# Netscape HTTP Cookie File\n# Generated by NetSanctum\n" + text
        text = text.replace("\r\n", "\n")
        if not text.endswith("\n"):
            text += "\n"
        fd, path = tempfile.mkstemp(suffix=".txt", text=True)
        with os.fdopen(fd, "w") as f:
            f.write(text)
        return path
    return None


@celery_app.task(bind=True)
def process_video_url_task(
    self,
    url: str,
    quality: str = "720",
    comments_enabled: bool = True,
    comments_type: str = "top",
    comments_limit: int = 20,
    comments_replies: bool = True,
    replies_limit: int = 5,
    auto_update: bool = False,
    cookies_text: str | None = None,
    playlist_id: int | None = None,
    compress_video: bool = False,
    download_subtitles: bool = False,
) -> str:
    """
    Entry point for archiving. Identifies if the URL is a playlist or single video.
    Dispatches separate download tasks accordingly.
    """
    task_id = self.request.id

    def update_status(status: str, title: str = "Resolving URL..."):
        data = {"task_id": task_id, "url": url, "title": title, "status": status, "progress": "0%"}
        redis_client.setex(f"video_dl:{task_id}", 86400, json.dumps(data))

    update_status("Fetching info...")

    try:
        provider = PlatformRegistry.require_supported_url(url)
    except ValueError as exc:
        update_status(str(exc), "Error")
        return f"Error: {exc}"
    if not cookies_text:
        cookies_text = _get_platform_cookies(provider.platform_id)

    ydl_opts = provider.get_ydl_opts(
        {
            "quiet": True,
            "extract_flat": "in_playlist",
            "js_runtimes": {"deno": {}},
        }
    )

    cookie_path = _create_temp_cookies_file(cookies_text)
    if cookie_path:
        ydl_opts["cookiefile"] = cookie_path

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info_dict = ydl.extract_info(url, download=False)
    except Exception as e:
        logger.error(f"Error fetching info for URL {url}: {e}")
        update_status(f"Error: {str(e)[:50]}...", "Error")
        return f"Error: {e}"
    finally:
        if cookie_path and os.path.exists(cookie_path):
            os.remove(cookie_path)

    if "entries" in info_dict:
        # It's a playlist
        playlist_title = info_dict.get("title", "Unknown Playlist")
        playlist_description = info_dict.get("description", "")

        if playlist_id is None:
            with SyncSessionLocal() as session:
                playlist = VideoPlaylist(name=playlist_title, description=playlist_description)
                session.add(playlist)
                session.commit()
                session.refresh(playlist)
                playlist_id = playlist.id

        entries = list(info_dict["entries"])
        logger.info(f"Playlist detected: {playlist_title} with {len(entries)} videos.")

        for _i, entry in enumerate(entries):
            video_id = entry.get("id")
            if not video_id:
                continue
            video_url = f"https://www.youtube.com/watch?v={video_id}"

            # Spawn task for each video in the playlist
            dispatch_tracked_sync(
                download_video_task,
                redis_client,
                "video_dl",
                {
                    "url": video_url,
                    "title": entry.get("title", f"Video {video_id}"),
                    "status": "Queued",
                    "progress": "0%",
                },
                kwargs={
                    "url": video_url,
                    "quality": quality,
                    "comments_enabled": comments_enabled,
                    "comments_type": comments_type,
                    "comments_limit": comments_limit,
                    "comments_replies": comments_replies,
                    "replies_limit": replies_limit,
                    "auto_update": auto_update,
                    "cookies_text": cookies_text,
                    "playlist_id": playlist_id,
                    "compress_video": compress_video,
                    "download_subtitles": download_subtitles,
                },
            )

        redis_client.delete(f"video_dl:{task_id}")
        return f"Dispatched {len(entries)} videos for playlist '{playlist_title}'"
    else:
        # Single video
        video_id = info_dict.get("id")
        task = dispatch_tracked_sync(
            download_video_task,
            redis_client,
            "video_dl",
            {"url": url, "title": str(video_id or url), "status": "Queued", "progress": "0%"},
            kwargs={
                "url": url,
                "quality": quality,
                "comments_enabled": comments_enabled,
                "comments_type": comments_type,
                "comments_limit": comments_limit,
                "comments_replies": comments_replies,
                "replies_limit": replies_limit,
                "auto_update": auto_update,
                "cookies_text": cookies_text,
                "playlist_id": playlist_id,
                "compress_video": compress_video,
                "download_subtitles": download_subtitles,
            },
        )
        # Delete the resolver task tracker immediately since the child downloader task has registered its own tracker
        redis_client.delete(f"video_dl:{task_id}")
        return f"Dispatched single video download task: {task.id}"


@celery_app.task(bind=True)
def download_video_task(
    self,
    url: str,
    quality: str = "720",
    comments_enabled: bool = True,
    comments_type: str = "top",
    comments_limit: int = 20,
    comments_replies: bool = True,
    replies_limit: int = 5,
    auto_update: bool = False,
    cookies_text: str | None = None,
    playlist_id: int | None = None,
    compress_video: bool = False,
    download_subtitles: bool = False,
) -> str:
    """Downloads a single video, caches metadata + comments, and saves to database."""
    task_id = self.request.id

    def update_redis(status: str, progress: str = "0%", title: str = "Downloading..."):
        data = {"task_id": task_id, "url": url, "title": title, "status": status, "progress": progress}
        redis_client.setex(f"video_dl:{task_id}", 86400, json.dumps(data))

    # Helper hook to monitor yt-dlp progress
    def ydl_progress_hook(d):
        if d["status"] == "downloading":
            total = d.get("total_bytes") or d.get("total_bytes_estimate") or 0
            downloaded = d.get("downloaded_bytes", 0)
            if total > 0:
                pct = int((downloaded / total) * 100)
                update_redis("Downloading video stream", f"{pct}%")
        elif d["status"] == "finished":
            update_redis("Processing video format", "99%")

    update_redis("Extracting full metadata...", "5%")

    temp_dir = tempfile.mkdtemp()
    try:
        provider = PlatformRegistry.require_supported_url(url)
    except ValueError as exc:
        update_redis(str(exc), "Error")
        return f"Error: {exc}"
    if not cookies_text:
        cookies_text = _get_platform_cookies(provider.platform_id)

    cookie_path = _create_temp_cookies_file(cookies_text)

    # Configure yt-dlp options using platform provider strategy
    ydl_opts = provider.get_ydl_opts(
        {
            "format": f"bestvideo[height<={quality}][ext=mp4]+bestaudio[ext=m4a]/best[height<={quality}][ext=mp4]/best[height<={quality}]/best",
            "outtmpl": os.path.join(temp_dir, "%(id)s.%(ext)s"),
            "merge_output_format": "mp4",
            "progress_hooks": [ydl_progress_hook],
            "getcomments": comments_enabled,
            "extractor_retries": 1,
            "js_runtimes": {"deno": {}},
            "ignoreerrors": True,
        }
    )

    if cookie_path:
        ydl_opts["cookiefile"] = cookie_path

    if download_subtitles:
        ydl_opts["writesubtitles"] = True
        ydl_opts["writeautomaticsub"] = False  # Manual subtitles only (human-added, not auto-generated)
        ydl_opts["subtitleslangs"] = ["all"]
        ydl_opts["subtitlesformat"] = "vtt"

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info_dict = ydl.extract_info(url, download=True)

        if not info_dict:
            raise Exception("Failed to download media: yt-dlp extraction returned no data.")

        video_id = info_dict.get("id")
        title = info_dict.get("title", "Untitled Video")
        update_redis("Archiving metadata & files", "90%", title=title)

        # Locate the downloaded file
        downloaded_file = None
        for filename in os.listdir(temp_dir):
            if filename.startswith(video_id) and filename.endswith(".mp4"):
                downloaded_file = os.path.join(temp_dir, filename)
                break

        if not downloaded_file:
            # Try to find any downloaded file and transcode/rename
            for filename in os.listdir(temp_dir):
                if filename.startswith(video_id):
                    downloaded_file = os.path.join(temp_dir, filename)
                    break

        if not downloaded_file or not os.path.exists(downloaded_file):
            raise FileNotFoundError("Could not locate downloaded video file.")

        # Compress video via FFmpeg if requested
        if compress_video:
            update_redis("Compressing video (FFmpeg)", "95%", title=title)
            compressed_file = os.path.join(temp_dir, f"compressed_{video_id}.mp4")
            try:
                import subprocess

                cmd = [
                    "ffmpeg",
                    "-y",
                    "-i",
                    downloaded_file,
                    "-vcodec",
                    "libx264",
                    "-crf",
                    "28",
                    "-preset",
                    "fast",
                    "-acodec",
                    "aac",
                    "-b:a",
                    "128k",
                    compressed_file,
                ]
                logger.info(f"Running compression command: {' '.join(cmd)}")
                subprocess.run(cmd, capture_output=True, text=True, check=True)
                if os.path.exists(compressed_file) and os.path.getsize(compressed_file) > 0:
                    os.remove(downloaded_file)
                    downloaded_file = compressed_file
                    logger.info("FFmpeg compression completed successfully.")
                else:
                    logger.warning(
                        "FFmpeg compression output was missing or empty. Falling back to original file."
                    )
            except Exception as compress_err:
                logger.error(
                    f"FFmpeg compression failed, falling back to original video file: {compress_err}"
                )

        # Save video to storage abstraction layer
        storage = get_storage()
        with open(downloaded_file, "rb") as f:
            video_bytes = f.read()

        video_storage_path = f"video_archiver/videos/{video_id}.mp4"
        storage.save_file(video_bytes, video_storage_path)
        os.remove(downloaded_file)

        # Download thumbnail
        thumbnail_storage_path = None
        thumbnail_url = info_dict.get("thumbnail")
        if thumbnail_url:
            try:
                content, content_type, _ = fetch_bytes_checked(
                    thumbnail_url,
                    allowed_hosts=VIDEO_IMAGE_HOSTS,
                )
                ext = (
                    "webp"
                    if content_type == "image/webp"
                    else "png"
                    if content_type == "image/png"
                    else "jpg"
                )
                thumbnail_storage_path = f"video_archiver/thumbnails/{video_id}.{ext}"
                storage.save_file(content, thumbnail_storage_path)
            except (RemoteFetchError, OSError) as thumbnail_err:
                logger.warning(f"Failed to download thumbnail: {thumbnail_err}")

        # Collect and save subtitles if downloaded
        subtitles_map = {}
        if download_subtitles:
            update_redis("Extracting subtitles", "97%", title=title)
            try:
                for filename in os.listdir(temp_dir):
                    if filename.startswith(video_id) and filename.endswith(".vtt"):
                        parts = filename.split(".")
                        if len(parts) >= 3:
                            lang = parts[-2]
                            subtitle_file = os.path.join(temp_dir, filename)
                            with open(subtitle_file, "rb") as sub_f:
                                subtitle_bytes = sub_f.read()

                            sub_storage_path = f"video_archiver/subtitles/{video_id}.{lang}.vtt"
                            storage.save_file(subtitle_bytes, sub_storage_path)
                            subtitles_map[lang] = sub_storage_path
                            logger.info(f"Saved subtitle for {lang} to {sub_storage_path}")
            except Exception as sub_err:
                logger.error(f"Failed to process subtitles: {sub_err}")

        # Extract comments
        comments = []
        if comments_enabled and "comments" in info_dict:
            raw_comments = info_dict["comments"]
            # Separate root comments and replies
            roots = [c for c in raw_comments if c.get("parent", "root") == "root"]
            replies_map = {}
            for c in raw_comments:
                p = c.get("parent")
                if p and p != "root":
                    replies_map.setdefault(p, []).append(c)

            for c in roots[:comments_limit]:
                c_id = c.get("id")
                comment_item = {
                    "author": c.get("author", "Unknown"),
                    "text": c.get("text", ""),
                    "likes": c.get("like_count", 0),
                    "time": c.get("time_text", ""),
                    "replies": [],
                }
                if comments_replies and c_id in replies_map:
                    for r in replies_map[c_id][:replies_limit]:
                        comment_item["replies"].append(
                            {
                                "author": r.get("author", "Unknown"),
                                "text": r.get("text", ""),
                                "likes": r.get("like_count", 0),
                                "time": r.get("time_text", ""),
                            }
                        )
                comments.append(comment_item)

        # Save / Update Database
        with SyncSessionLocal() as session:
            channel = _get_or_create_channel(session, info_dict)
            video = session.get(ArchivedVideo, video_id)
            if not video:
                video = ArchivedVideo(id=video_id)
                session.add(video)

            platform = PlatformRegistry.detect_platform(
                url, info_dict.get("extractor_key") or info_dict.get("extractor")
            )
            video.title = title
            video.description = info_dict.get("description")
            video.platform = platform
            video.channel_name = channel.name if channel else info_dict.get("uploader", "Unknown Channel")
            video.channel_id = (
                channel.id if channel else info_dict.get("uploader_id") or info_dict.get("channel_id")
            )
            if channel and channel.avatar_path:
                video.channel_avatar_url = channel.avatar_path
            video.duration = int(info_dict.get("duration") or 0)
            video.resolution = f"{quality}p"
            video.file_path = video_storage_path
            video.thumbnail_path = thumbnail_storage_path
            video.status = "completed"
            video.comments = comments
            video.subtitles = subtitles_map
            video.auto_update = auto_update
            video.is_deleted_on_youtube = False
            video.like_count = info_dict.get("like_count")
            video.view_count = info_dict.get("view_count")
            video.tags = info_dict.get("tags")

            publish_date_str = info_dict.get("upload_date")
            if publish_date_str:
                try:
                    video.original_publish_date = datetime.datetime.strptime(publish_date_str, "%Y%m%d")
                except ValueError:
                    pass

            if playlist_id:
                playlist = session.get(VideoPlaylist, playlist_id)
                if playlist and playlist not in video.playlists:
                    video.playlists.append(playlist)

            session.commit()

        update_redis("Completed", "100%", title=title)
        redis_client.delete(f"video_dl:{task_id}")
        return f"Successfully archived video {video_id}"

    except Exception as e:
        err_msg = str(e)
        logger.error(f"Failed to process video {url}: {err_msg}")

        if "Sign in to confirm" in err_msg or "cookie" in err_msg.lower():
            status_msg = "Failed: Cookies are outdated or invalid. Please update."
        else:
            status_msg = f"Failed: {err_msg[:50]}..."

        update_redis(status_msg, "Error")
        return f"Error downloading video: {err_msg}"
    finally:
        # Clean up temporary directory
        if cookie_path and os.path.exists(cookie_path):
            os.remove(cookie_path)
        try:
            for root, dirs, files in os.walk(temp_dir, topdown=False):
                for name in files:
                    os.remove(os.path.join(root, name))
                for name in dirs:
                    os.rmdir(os.path.join(root, name))
            os.rmdir(temp_dir)
        except Exception:
            pass


def _get_or_create_channel(session, info_dict: dict | None) -> VideoChannel | None:
    """Fetch or create VideoChannel entity and download avatar if available."""
    if not info_dict:
        return None

    channel_id = info_dict.get("uploader_id") or info_dict.get("channel_id")
    if not channel_id:
        return None

    channel_name = info_dict.get("uploader") or info_dict.get("channel") or "Unknown Channel"

    platform = PlatformRegistry.detect_platform(
        info_dict.get("webpage_url", ""), info_dict.get("extractor_key") or info_dict.get("extractor")
    )
    channel = session.get(VideoChannel, channel_id)
    if not channel:
        channel = VideoChannel(
            id=channel_id,
            name=channel_name,
            platform=platform,
            custom_url=info_dict.get("uploader_url") or info_dict.get("channel_url"),
        )
        session.add(channel)
        session.flush()
    else:
        if channel_name and channel.name != channel_name and channel_name != "Unknown Channel":
            channel.name = channel_name
        if platform and channel.platform != platform:
            channel.platform = platform

    avatar_url = (
        info_dict.get("channel_thumbnail")
        or info_dict.get("uploader_avatar")
        or info_dict.get("channel_avatar")
    )
    if not avatar_url:
        for t in info_dict.get("thumbnails") or []:
            u = t.get("url", "")
            if "yt3.googleusercontent.com" in u or "yt3.ggpht.com" in u:
                avatar_url = u
                break

    if avatar_url:
        try:
            content, content_type, _ = fetch_bytes_checked(
                avatar_url,
                allowed_hosts=VIDEO_IMAGE_HOSTS,
            )
            storage = get_storage()
            ext = "webp" if content_type == "image/webp" else "png" if content_type == "image/png" else "jpg"
            avatar_storage_path = f"video_archiver/avatars/{channel_id}.{ext}"
            storage.save_file(content, avatar_storage_path)
            channel.avatar_path = avatar_storage_path
        except (RemoteFetchError, OSError) as err:
            logger.warning(f"Failed to download channel avatar for {channel_id}: {err}")

    return channel


def _download_channel_avatar(info_dict: dict, channel_id: str) -> str | None:
    """Compatibility wrapper for channel avatar fetching."""
    with SyncSessionLocal() as session:
        ch = _get_or_create_channel(session, info_dict)
        if ch:
            session.commit()
            return ch.avatar_path
    return None


def _sync_video_metadata(video_id: str, task_id: str | None = None) -> str:
    """Checks if a video still exists and refreshes metadata using correct platform context."""
    with SyncSessionLocal() as session:
        video = session.get(ArchivedVideo, video_id)
        if not video:
            return "Video not found in local database."

        platform_id = video.platform or "youtube"

    provider = PlatformRegistry.get_provider_by_id(platform_id)
    url = provider.build_video_url(video_id)
    cookies_text = _get_platform_cookies(platform_id)

    if task_id:
        data = {
            "task_id": task_id,
            "url": url,
            "title": f"Syncing {video_id}",
            "status": "Fetching Metadata...",
            "progress": "50%",
        }
        redis_client.setex(f"video_dl:{task_id}", 86400, json.dumps(data))

    # Configure yt-dlp options using platform provider strategy
    ydl_opts = provider.get_ydl_opts(
        {
            "quiet": True,
            "getcomments": False,  # Skip comments during background sync to avoid YouTube rate-limiting / slow retries
            "extractor_retries": 0,
            "ignoreerrors": True,
            "js_runtimes": {"deno": {}},
        }
    )

    cookie_path = _create_temp_cookies_file(cookies_text)
    if cookie_path:
        ydl_opts["cookiefile"] = cookie_path

    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info_dict = ydl.extract_info(url, download=False)

        if not info_dict:
            raise yt_dlp.utils.DownloadError("No data received. Possibly blocked by authentication wall.")

        # Update database with fresh metadata
        with SyncSessionLocal() as session:
            channel = _get_or_create_channel(session, info_dict)
            video = session.get(ArchivedVideo, video_id)
            if video:
                video.title = info_dict.get("title", video.title)
                video.description = info_dict.get("description", video.description)
                if channel:
                    video.channel_id = channel.id
                    video.channel_name = channel.name
                    if channel.avatar_path:
                        video.channel_avatar_url = channel.avatar_path
                video.is_deleted_on_youtube = False
                video.like_count = info_dict.get("like_count", video.like_count)
                video.view_count = info_dict.get("view_count", video.view_count)
                video.tags = info_dict.get("tags", video.tags)

                # Update comments
                comments = []
                if "comments" in info_dict:
                    # Keep same count
                    comments_limit = len(video.comments) if video.comments else 20
                    for c in info_dict["comments"][:comments_limit]:
                        comments.append(
                            {
                                "author": c.get("author", "Unknown"),
                                "text": c.get("text", ""),
                                "likes": c.get("like_count", 0),
                                "time": c.get("time_text", ""),
                            }
                        )
                    video.comments = comments
                session.commit()
        return f"Successfully synced video {video_id}"

    except Exception as e:
        # Check if error implies video is deleted or private
        err_msg = str(e).lower()
        if "sign in" in err_msg or "login" in err_msg or "confirm you" in err_msg:
            with SyncSessionLocal() as session:
                video = session.get(ArchivedVideo, video_id)
                if video:
                    video.status = "auth_required"
                    session.commit()
            return f"Failed to sync video {video_id}: Auth required. Check {platform_id}_cookies."
        elif "unavailable" in err_msg or "private" in err_msg or "removed" in err_msg or "404" in err_msg:
            with SyncSessionLocal() as session:
                video = session.get(ArchivedVideo, video_id)
                if video:
                    video.is_deleted_on_youtube = True
                    session.commit()
            if task_id:
                redis_client.delete(f"video_dl:{task_id}")
            return f"Video {video_id} is unavailable on remote platform. Marked as deleted."
        else:
            if task_id:
                redis_client.delete(f"video_dl:{task_id}")
            return f"Failed to sync video {video_id}: {e}"
    finally:
        if "cookie_path" in locals() and cookie_path and os.path.exists(cookie_path):
            os.remove(cookie_path)
        if "task_id" in locals() and task_id:
            redis_client.delete(f"video_dl:{task_id}")


@celery_app.task(bind=True)
def sync_video_metadata_task(self, video_id: str) -> str:
    return _sync_video_metadata(video_id, self.request.id)


class OAuth2Logger:
    def __init__(self, task_id):
        self.task_id = task_id

    def debug(self, msg):
        pass

    def info(self, msg):
        pass

    def error(self, msg):
        pass

    def warning(self, msg):
        if "google.com/device" in msg:
            redis_client.setex(
                f"video_oauth:{self.task_id}", 3600, json.dumps({"status": "pending", "message": msg})
            )


@celery_app.task(bind=True)
def youtube_oauth2_task(self) -> str:
    """Initiates YouTube OAuth2 device flow to cache a permanent token."""
    task_id = self.request.id
    redis_client.setex(f"video_oauth:{task_id}", 3600, json.dumps({"status": "starting"}))

    ydl_opts = {
        "cachedir": "/app/storage/.cache/yt-dlp",
        "username": "oauth2",
        "password": "",
        "logger": OAuth2Logger(task_id),
        "extract_flat": True,
        "quiet": True,
    }
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            # We just need to trigger an extraction that requires auth or checks it
            # Fetching a known video to trigger token generation
            ydl.extract_info("https://www.youtube.com/watch?v=BaW_jenozKc", download=False)
        redis_client.setex(f"video_oauth:{task_id}", 3600, json.dumps({"status": "success"}))

        # Touch the flag file so YouTubeProvider knows to use oauth2
        with open("/app/storage/.youtube_oauth_enabled", "w") as f:
            f.write("1")

        return "OAuth2 token generated and cached."
    except Exception as e:
        redis_client.setex(f"video_oauth:{task_id}", 3600, json.dumps({"status": "error", "message": str(e)}))
        return f"OAuth2 failed: {e}"


@celery_app.task(bind=True)
def sync_all_videos_task(self, dates: list[str] | None = None) -> str:
    """Syncs metadata for all completed local videos synchronously with global progress."""
    task_id = self.request.id or "global_sync"

    with SyncSessionLocal() as session:
        all_videos = session.scalars(select(ArchivedVideo).where(ArchivedVideo.status == "completed")).all()

        videos = []
        for v in all_videos:
            is_never = v.updated_at == v.archived_at or not v.updated_at
            d_str = v.updated_at.strftime("%Y-%m-%d") if v.updated_at else None

            if dates is None:
                videos.append(v.id)
                continue

            if len(dates) == 0:
                continue

            if "never" in dates and is_never:
                videos.append(v.id)
                continue

            if not is_never and d_str in dates:
                videos.append(v.id)

    total = len(videos)
    if total == 0:
        return "No videos to sync."

    def update_progress(current, success, failed, current_vid, step_name="Updating metadata"):
        data = {
            "task_id": task_id,
            "url": "sync_all",
            "title": f"Global Metadata Sync ({step_name})",
            "status": f"{current} of {total} processed. Success: {success}, Failed: {failed}",
            "progress": f"{int((current / total) * 100)}%",
            "type": "global_sync",
            "success_count": success,
            "failed_count": failed,
            "total_count": total,
            "current_video": current_vid,
        }
        redis_client.setex(f"video_dl:{task_id}", 86400, json.dumps(data))

    success_count = 0
    failed_count = 0
    update_progress(0, 0, 0, "")

    for i, vid_id in enumerate(videos, 1):
        try:
            res = _sync_video_metadata(vid_id)
            if "Auth required" in res:
                failed_count += 1
                update_progress(i, success_count, failed_count, vid_id, "Aborted: Auth Required")
                return "Sync aborted due to expired cookies."
            elif "Failed" in res:
                failed_count += 1
            else:
                success_count += 1
        except Exception:
            failed_count += 1

        update_progress(i, success_count, failed_count, vid_id)

        # Anti-bot delay
        if i < total:
            time.sleep(random.uniform(4.0, 9.0))

    # Allow UI to show final state for a while before cleaning up
    update_progress(total, success_count, failed_count, "", "Finished")

    return f"Synced {total} videos. Success: {success_count}, Failed: {failed_count}."
