from app.core.module_types import (
    IntegrationSpec,
    MigrationSpec,
    ModuleSpec,
    ShareAsset,
    ShareRoute,
    ShareSpec,
)

MODULE = ModuleSpec(
    id="alllib",
    version="0.1.0",
    title_en="Lib Network",
    title_ru="Lib Сеть",
    dashboard_url="/alllib/dashboard",
    order=40,
    router="app.modules.alllib.router:router",
    models="app.modules.alllib.models",
    migrations=MigrationSpec(
        path="migrations",
        baseline_revision="alllib_0001",
        tables=("lib_media", "lib_chapters"),
        legacy_tables=("lib_media", "lib_chapters"),
    ),
    tasks="app.modules.alllib.tasks",
    templates="templates",
    i18n="app.modules.alllib.i18n",
    file_cleanup="app.modules.alllib.cleanup:cleanup_file",
    module_cleanup="app.modules.alllib.cleanup:cleanup_module",
    storage_namespaces=("alllib", "ranobelib"),
    package_prefixes=("manga_", "novel_", "anime_"),
    package_resolver="app.modules.alllib.capabilities:resolve_package_resources",
    share=ShareSpec(
        provider="app.modules.alllib.share:PROVIDER",
        selector_key="media_ids",
        dashboard_template="alllib_dashboard.html",
        api_prefix="/api/alllib",
        routes=(
            ShareRoute(name="media", path="media"),
            ShareRoute(name="media_detail", path="media/{media_id}"),
            ShareRoute(name="library", path="library"),
            ShareRoute(name="library_tab", path="library-tab"),
            ShareRoute(name="detail", path="media/{media_id}/detail"),
            ShareRoute(name="reader", path="media/{media_id}/reader"),
            ShareRoute(
                name="chapters",
                path="media/{media_id}/chapters",
                source="relations",
            ),
            ShareRoute(name="chapter", path="chapters/{chapter_id}", source="relations"),
        ),
        assets=(
            ShareAsset(name="cover", path="media/{media_id}/cover"),
            ShareAsset(name="chapter_page", path="chapters/{chapter_id}/pages/{page_index}"),
            ShareAsset(name="chapter_video", path="chapters/{chapter_id}/video"),
            ShareAsset(name="export", path="media/{media_id}/export"),
        ),
    ),
    entity_types=("manga", "ranobe", "anime"),
    entity_resolver="app.modules.alllib.capabilities:resolve_entity",
    integrations=(
        IntegrationSpec(
            id="alllib.library.viewer.v1",
            contract="library.viewer.v1",
            handler="app.modules.alllib.integrations:library_viewer",
            request_model="app.contracts.library_viewer_v1:LibraryRequest",
            result_model="app.contracts.library_viewer_v1:LibraryResult",
            resource_handler="app.modules.alllib.integrations:resolve_library_resource",
            resource_request_model="app.contracts.library_viewer_v1:LibraryResourceRequest",
        ),
    ),
    progress_key_patterns=("alllib_dl:*",),
    dependency_extra="alllib",
    system_packages=("ffmpeg",),
)
